# Generated by Django 6.0.4 on 2026-04-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0014_messagereaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelgroup",
            name="note",
            field=models.TextField(blank=True),
        ),
    ]
