# Generated by Django 6.0.4 on 2026-04-30 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0015_add_channelgroup_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelVacancy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("_created", models.DateTimeField(auto_now_add=True)),
                ("_updated", models.DateTimeField(auto_now=True)),
                ("death_date", models.DateField()),
                ("note", models.TextField(blank=True)),
                (
                    "channel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="vacancy", to="webapp.channel"
                    ),
                ),
            ],
            options={
                "ordering": ["-death_date"],
            },
        ),
    ]
