# Generated by Django 6.0.4 on 2026-05-03 06:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0017_rename_death_date_channelvacancy_closure_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="channelvacancy",
            options={"ordering": ["-closure_date"]},
        ),
    ]
