# Generated by Django 6.0.4 on 2026-05-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0018_alter_channelvacancy_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="uninteresting_after",
            field=models.DateField(blank=True, null=True),
        ),
    ]
