# Generated by Django 6.0.4 on 2026-05-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0024_add_message_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="antispam",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="channel",
            name="banned_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="channel",
            name="boosts_applied",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="channel",
            name="boosts_unrestrict",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="channel",
            name="has_scheduled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="channel",
            name="kicked_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="channel",
            name="migrated_from_chat_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="channel",
            name="pinned_msg_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="factcheck",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="fwd_from_channel_post",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="fwd_from_from_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="message",
            name="replies",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="reply_to_msg_id",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="silent",
            field=models.BooleanField(default=False),
        ),
    ]
