# Generated by Django 6.0.4 on 2026-05-07 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0025_add_telethon_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageReply",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("telegram_id", models.BigIntegerField()),
                ("date", models.DateTimeField(null=True)),
                ("text", models.TextField(blank=True)),
                ("sender_name", models.CharField(blank=True, max_length=255)),
                ("sender_id", models.BigIntegerField(null=True)),
                ("views", models.PositiveBigIntegerField(null=True)),
                (
                    "parent_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reply_set", to="webapp.message"
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("parent_message", "telegram_id")},
            },
        ),
    ]
