# Generated by Django 6.0.4 on 2026-05-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0027_add_poll"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="replies_unavailable",
            field=models.BooleanField(default=False),
        ),
    ]
