# Generated by Django 6.0.5 on 2026-05-21 05:28

from django.db import migrations, models

import webapp.models.base


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0042_replace_in_target_override_with_to_inspect"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messageaudio",
            name="audio",
            field=models.FileField(
                max_length=255,
                storage=webapp.models.base.OverwriteStorage(),
                upload_to=webapp.models.base._telegram_picture_upload_to_function,
            ),
        ),
        migrations.AlterField(
            model_name="messageothermedia",
            name="media_file",
            field=models.FileField(
                max_length=255,
                storage=webapp.models.base.OverwriteStorage(),
                upload_to=webapp.models.base._telegram_picture_upload_to_function,
            ),
        ),
        migrations.AlterField(
            model_name="messagepicture",
            name="picture",
            field=models.ImageField(
                max_length=255,
                storage=webapp.models.base.OverwriteStorage(),
                upload_to=webapp.models.base._telegram_picture_upload_to_function,
            ),
        ),
        migrations.AlterField(
            model_name="messagesticker",
            name="sticker",
            field=models.FileField(
                max_length=255,
                storage=webapp.models.base.OverwriteStorage(),
                upload_to=webapp.models.base._telegram_picture_upload_to_function,
            ),
        ),
        migrations.AlterField(
            model_name="messagevideo",
            name="video",
            field=models.FileField(
                max_length=255,
                storage=webapp.models.base.OverwriteStorage(),
                upload_to=webapp.models.base._telegram_picture_upload_to_function,
            ),
        ),
        migrations.AlterField(
            model_name="profilepicture",
            name="picture",
            field=models.ImageField(
                max_length=255,
                storage=webapp.models.base.OverwriteStorage(),
                upload_to=webapp.models.base._telegram_picture_upload_to_function,
            ),
        ),
        migrations.AlterField(
            model_name="profilepicture",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                max_length=255,
                storage=webapp.models.base.OverwriteStorage(),
                upload_to=webapp.models.base._telegram_picture_upload_to_function,
            ),
        ),
    ]
