# Generated by Django 6.0.5 on 2026-06-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0049_remove_channel_org_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("_created", models.DateTimeField(auto_now_add=True)),
                ("_updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, default="Pulpit project", max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("criteria", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Project",
            },
        ),
    ]
