# Generated by Django 6.0.5 on 2026-06-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0052_clear_spurious_user_account_flags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="webpage_url",
            field=models.URLField(blank=True, default="", max_length=2048),
        ),
    ]
