# Generated by Django 6.0.6 on 2026-06-14 13:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0055_seed_organization_labels"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="channelattribution",
            name="webapp_chattr_chan_org_idx",
        ),
        migrations.RemoveIndex(
            model_name="channelattribution",
            name="webapp_chattr_org_idx",
        ),
        migrations.RemoveIndex(
            model_name="channelattribution",
            name="webapp_chattr_chan_span_idx",
        ),
        migrations.DeleteModel(
            name="ChannelAttribution",
        ),
        migrations.DeleteModel(
            name="Organization",
        ),
    ]
