# Generated by Django 6.0.6 on 2026-06-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0057_rename_channelgroup_to_channelsource"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["channel", "grouped_id", "telegram_id"], name="webapp_msg_album_sib_idx"),
        ),
    ]
