# Generated by Django 6.0.6 on 2026-07-03 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0058_message_webapp_msg_album_sib_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelvacancy",
            name="successor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="succeeded_vacancies",
                to="webapp.channel",
            ),
        ),
    ]
