# Generated by Django 6.0.6 on 2026-08-06 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0059_channelvacancy_successor"),
    ]

    operations = [
        migrations.AddField(
            model_name="labelgroup",
            name="is_container",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="LabelParent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("_created", models.DateTimeField(auto_now_add=True)),
                ("_updated", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="parent_links", to="webapp.label"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="child_links", to="webapp.label"
                    ),
                ),
                (
                    "parent_group",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="webapp.labelgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["parent_id", "id"],
                "indexes": [models.Index(fields=["parent"], name="webapp_lblparent_parent_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("label", "parent_group"), name="webapp_lblparent_lbl_grp_uniq")
                ],
            },
        ),
    ]
