# Generated by Django 6.1 on 2026-08-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0060_labelgroup_is_container_labelparent"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="environment_depth",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
