# Generated by Django 6.1.1 on 2026-10-06 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import webapp.models.tag_models

import colorfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0061_channel_environment_depth"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("_created", models.DateTimeField(auto_now_add=True)),
                ("_updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64)),
                ("key", models.CharField(editable=False, max_length=64, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default=webapp.models.tag_models.next_tag_color, image_field=None, max_length=25, samples=None
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="MessageTagging",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("_created", models.DateTimeField(auto_now_add=True)),
                ("_updated", models.DateTimeField(auto_now=True)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="taggings", to="webapp.message"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="taggings", to="webapp.messagetag"
                    ),
                ),
                (
                    "tagged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_taggings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["tag__key"],
                "constraints": [
                    models.UniqueConstraint(fields=("message", "tag"), name="webapp_messagetagging_unique")
                ],
            },
        ),
    ]
