# Generated by Django 6.1.1 on 2026-10-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0063_message_tags_follow_shares"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="history_coverage",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                condition=models.Q(("pending_forward_telegram_id__isnull", False)),
                fields=["pending_forward_telegram_id", "fwd_from_channel_post"],
                name="webapp_msg_fwd_pending_idx",
            ),
        ),
    ]
