# Generated by Django 6.1.1 on 2026-10-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0066_channel_history_coverage_init"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="reply_to_peer_id",
            field=models.BigIntegerField(null=True),
        ),
    ]
